// Generated by CoffeeScript 1.6.2
(function() {
  var animate_at_startup, enable_auto_transitions, vendors;

  animate_at_startup = false;

  enable_auto_transitions = true;

  vendors = [];

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
