// Generated by CoffeeScript 1.6.3
(function() {
  var cs, cs_nodes, merge, prettyErrorMessage, vm, _ref;

  vm = require('vm');

  cs = require('coffee-script');

  cs_nodes = require('coffee-script/lib/coffee-script/nodes');

  _ref = require('coffee-script/lib/coffee-script/helpers'), merge = _ref.merge, prettyErrorMessage = _ref.prettyErrorMessage;

  module.exports = function(input, context, filename, cb) {
    var Assign, Block, Literal, Value, ast, err, js;
    input = input.replace(/\uFF00/g, '\n');
    input = input.replace(/^\(([\s\S]*)\n\)$/m, '$1');
    Block = cs_nodes.Block, Assign = cs_nodes.Assign, Value = cs_nodes.Value, Literal = cs_nodes.Literal;
    try {
      ast = cs.nodes(input);
      ast = new Block([new Assign(new Value(new Literal('_')), ast, '=')]);
      js = ast.compile({
        bare: true,
        locals: Object.keys(context)
      });
      return cb(null, vm.runInContext(js, context, filename));
    } catch (_error) {
      err = _error;
      return cb(prettyErrorMessage(err, filename, input, true));
    }
  };

}).call(this);

/*
//@ sourceMappingURL=repl-cs.map
*/
