// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.AppModel = (function(_super) {
    __extends(AppModel, _super);

    function AppModel() {
      _ref = AppModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return AppModel;

  })(theoricus.mvc.Model);

}).call(this);

/*
//@ sourceMappingURL=app_model.map
*/
