// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.models.Main = (function(_super) {
    __extends(Main, _super);

    function Main() {
      _ref = Main.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return Main;

  })(app.AppModel);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
