// Generated by CoffeeScript 1.6.2
(function() {
  var Model, path;

  path = require('path');

  module.exports = Model = (function() {
    var fs;

    fs = require('fs');

    function Model(the, name) {
      var contents, controller_name_lc, filepath, models, name_camel, name_lc, tmpl;

      this.the = the;
      name_camel = name.camelize();
      name_lc = name.toLowerCase();
      controller_name_lc = name.pluralize().toLowerCase();
      tmpl = path.join(this.the.root, 'cli', 'templates', 'mvc', 'model.coffee');
      models = path.join(this.the.app_root, 'src', 'app', 'models');
      filepath = path.join(models, "" + (name.toLowerCase()) + ".coffee");
      contents = (fs.readFileSync(tmpl)).toString();
      contents = contents.replace(/~NAME_CAMEL/g, name_camel);
      contents = contents.replace(/~CONTROLLER_LC/g, controller_name_lc);
      if (!fs.existsSync(filepath)) {
        fs.writeFileSync(filepath, contents);
        console.log(("" + 'Created'.bold + " " + filepath).green);
      } else {
        console.log(("" + 'Already exists'.red.bold + " " + filepath).green);
      }
    }

    return Model;

  })();

}).call(this);

/*
//@ sourceMappingURL=model.map
*/
