// Generated by CoffeeScript 1.6.3
(function() {
  var Model, path;

  path = require('path');

  module.exports = Model = (function() {
    var fs;

    fs = require('fs');

    function Model(the, name, repl) {
      var contents, controller_name_lc, filepath, models, name_camel, name_lc, relative, tmpl;
      this.the = the;
      this.repl = repl;
      name_camel = name.camelize();
      name_lc = name.toLowerCase();
      controller_name_lc = name.pluralize().toLowerCase();
      tmpl = path.join(this.the.root, 'cli', 'templates', 'mvc', 'model.coffee');
      models = path.join(this.the.app_root, 'src', 'app', 'models');
      filepath = path.join(models, "" + (name.toLowerCase()) + ".coffee");
      relative = filepath.replace(this.the.app_root + '/', '');
      contents = (fs.readFileSync(tmpl)).toString();
      contents = contents.replace(/~NAME_CAMEL/g, name_camel);
      contents = contents.replace(/~CONTROLLER_LC/g, controller_name_lc);
      if (!fs.existsSync(filepath)) {
        fs.writeFileSync(filepath, contents);
        if (!this.repl) {
          console.log(("" + 'Created'.bold + " " + relative).green);
        }
      } else {
        (this.repl || console).error(("" + 'Already exists'.bold + " " + relative).yellow);
      }
    }

    return Model;

  })();

}).call(this);

/*
//@ sourceMappingURL=model.map
*/
