// Generated by CoffeeScript 1.6.2
(function() {
  var View, fs, fsu, path;

  fs = require('fs');

  fsu = require('fs-util');

  path = require('path');

  module.exports = View = (function() {
    function View(the, name, controller_name_lc, mvc, options) {
      var contents, e, name_camel, name_lc, shell, src, style_folder, style_path, styles_ext, template_folder, template_path, templates_ext, tmpl_mvc, tmpl_style, tmpl_template, tmpl_view, view_folder, view_path;

      this.the = the;
      if (mvc == null) {
        mvc = false;
      }
      shell = options.join(' ');
      templates_ext = shell.match(/--templates[\s]*([^\s]+)/);
      templates_ext = templates_ext != null ? templates_ext[1] : 'jade';
      styles_ext = shell.match(/--styles[\s]*([^\s]+)/);
      styles_ext = styles_ext != null ? styles_ext[1] : 'styl';
      name_camel = name.camelize();
      name_lc = name.toLowerCase();
      src = path.join(this.the.app_root, 'src');
      view_folder = path.join(src, "app/views/" + controller_name_lc);
      template_folder = path.join(src, "templates/" + controller_name_lc);
      style_folder = path.join(src, "styles/" + controller_name_lc);
      if (mvc) {
        view_path = "" + view_folder + "/index.coffee";
      } else {
        view_path = "" + view_folder + "/" + name_lc + ".coffee";
      }
      template_path = "" + template_folder + "/index." + templates_ext;
      style_path = "" + style_folder + "/index." + styles_ext;
      tmpl_mvc = "" + this.the.root + "/cli/templates/mvc";
      tmpl_view = "" + tmpl_mvc + "/view.coffee";
      tmpl_template = "" + tmpl_mvc + "/view." + templates_ext;
      tmpl_style = "" + tmpl_mvc + "/view." + styles_ext;
      try {
        fsu.mkdir_p(view_folder);
        fsu.mkdir_p(template_folder);
        fsu.mkdir_p(style_folder);
      } catch (_error) {
        e = _error;
      }
      contents = (fs.readFileSync(tmpl_view)).toString();
      contents = contents.replace(/~NAME_CAMEL/g, name_camel);
      contents = contents.replace(/~CONTROLLER_NAME_LC/g, controller_name_lc);
      fs.writeFileSync(view_path, contents);
      console.log(("" + 'Created'.bold + " " + view_path).green);
      if (!fs.existsSync(template_path)) {
        fs.writeFileSync(template_path, fs.readFileSync(tmpl_template));
        console.log(("" + 'Created'.bold + " " + template_path).green);
      } else {
        console.log(("" + 'Already exists'.bold + " " + template_path).green);
      }
      if (!fs.existsSync(style_path)) {
        fs.writeFileSync(style_path, fs.readFileSync(tmpl_style));
        console.log(("" + 'Created'.bold + " " + style_path).green);
      } else {
        console.log(("" + 'Already exists'.bold + " " + style_path).green);
      }
    }

    return View;

  })();

}).call(this);

/*
//@ sourceMappingURL=view.map
*/
