// Generated by CoffeeScript 1.6.2
(function() {
  var AddProject, exec, fs, path, pn, spawn;

  fs = require('fs');

  path = require('path');

  pn = path.normalize;

  exec = (require("child_process")).exec;

  spawn = (require("child_process")).spawn;

  module.exports = AddProject = (function() {
    function AddProject(the, cli) {
      var cmd,
        _this = this;

      this.the = the;
      this.cli = cli;
      if (this.cli.argv["new"] === true) {
        console.log("ERROR".bold.red + " You must specify a name for your project");
        return;
      }
      this.pwd = this.the.pwd;
      this.root = this.the.root;
      this.app_skel = path.join(this.the.root, 'cli', 'templates', 'app_skel');
      this.target = path.join(this.pwd, this.cli.argv["new"]);
      if (fs.existsSync(this.target)) {
        console.log("ERROR".bold.red + " Target directory already existis.");
        console.log("\n\t");
        console.log(("" + this.target).yellow);
        return;
      }
      cmd = "cp -r " + this.app_skel + " " + this.target;
      exec(cmd, function(error, stdout, stderr) {
        if (error != null) {
          return console.log(error);
        } else {
          return exec("find " + _this.target, function(error, stdout, stderr) {
            var file, files, _i, _len;

            files = stdout.split("\n").slice(0, -1);
            for (_i = 0, _len = files.length; _i < _len; _i++) {
              file = files[_i];
              console.log(("" + 'Created'.bold + " " + file).green);
            }
            console.log('\nApplication created, setting up...\n\n');
            return spawn('make', ['setup'], {
              cwd: _this.target,
              stdio: 'inherit'
            });
          });
        }
      });
    }

    return AddProject;

  })();

}).call(this);

/*
//@ sourceMappingURL=add_project.map
*/
