// Generated by CoffeeScript 1.6.3
(function() {
  var Compiler, fork, path, polvo;

  path = require('path');

  fork = (require('child_process')).fork;

  polvo = require('polvo');

  module.exports = Compiler = (function() {
    function Compiler(the, cli, release, webserver) {
      this.the = the;
      this.cli = cli;
      if (!this.the.is_theoricus_app()) {
        return;
      }
      polvo({
        compile: true,
        base: this.the.app_root
      });
    }

    return Compiler;

  })();

}).call(this);

/*
//@ sourceMappingURL=compiler.map
*/
