// Generated by CoffeeScript 1.6.3
(function() {
  var Compiler, fork, path, polvo;

  path = require('path');

  fork = (require('child_process')).fork;

  polvo = require('polvo');

  module.exports = Compiler = (function() {
    function Compiler(the, cli, release, webserver) {
      var options;
      this.the = the;
      this.cli = cli;
      if (!this.the.is_theoricus_app()) {
        return;
      }
      options = {
        base: this.the.app_root
      };
      if (release != null) {
        options.release = true;
      } else {
        options.compile = true;
      }
      if (webserver != null) {
        options.server = true;
      }
      polvo(options);
    }

    return Compiler;

  })();

}).call(this);

/*
//@ sourceMappingURL=compiler.map
*/
