// Generated by CoffeeScript 1.6.2
(function() {
  var Compiler, fork, path;

  path = require("path");

  fork = require("child_process").fork;

  module.exports = Compiler = (function() {
    function Compiler(the, options, release, webserver) {
      var opts;

      this.the = the;
      opts = '';
      opts += release != null ? '-r' : '-c';
      opts += webserver != null ? 's' : '';
      this.polvo_path = path.join(this.the.root, 'node_modules', 'polvo', 'bin', 'polvo');
      fork(this.polvo_path, [opts], {
        cwd: this.the.app_root
      });
    }

    return Compiler;

  })();

}).call(this);

/*
//@ sourceMappingURL=compiler.map
*/
