// Generated by CoffeeScript 1.6.2
(function() {
  var Rm, fs, fsu, path;

  fs = require('fs');

  path = require('path');

  fsu = require("fs-util");

  module.exports = Rm = (function() {
    function Rm(the, opts) {
      var error_msg, name, type;

      this.the = the;
      type = opts[1];
      name = opts[2];
      this.recursive = (opts[3] != null) && /\-\-rf/.test(opts[3]);
      this.APP_FOLDER = "" + this.the.pwd + "/app";
      if (this[type] == null) {
        error_msg = "Valid options: controller, model, view, mvc.";
        throw new Error(error_msg);
      }
      this[type](name);
    }

    Rm.prototype.mvc = function(name) {
      this.model(name.singularize());
      this.view("" + (name.singularize()) + "/index");
      return this.controller(name);
    };

    Rm.prototype.model = function(name) {
      return this.rm("" + this.APP_FOLDER + "/models/" + name + ".coffee");
    };

    Rm.prototype.view = function(path) {
      var error_msg, folder, name, parts;

      folder = (parts = path.split('/'))[0];
      name = parts[1];
      if (!((name != null) || this.recursive)) {
        error_msg = "Views should be removed with path-style notation.\n\n\ti.e.:\n\t\t theoricus rm view person/index\n\t\t theoricus rm view user/list\n";
        throw new Error(error_msg);
        return;
      }
      if (this.recursive) {
        this.rm("" + this.APP_FOLDER + "/views/" + folder);
        return this.rm("" + this.APP_FOLDER + "/static/" + folder);
      } else {
        this.rm("" + this.APP_FOLDER + "/views/" + folder + "/" + name + ".coffee");
        this.rm("" + this.APP_FOLDER + "/static/" + folder + "/" + name + ".jade");
        return this.rm("" + this.APP_FOLDER + "/static/" + folder + "/" + name + ".styl");
      }
    };

    Rm.prototype.controller = function(name, args, mvc) {
      if (mvc == null) {
        mvc = false;
      }
      return this.rm("" + this.APP_FOLDER + "/controllers/" + name + ".coffee");
    };

    Rm.prototype.rm = function(filepath) {
      var err, rpath;

      rpath = filepath.match(/app\/.*/);
      if (fs.existsSync(filepath)) {
        try {
          if (fs.lstatSync(filepath).isDirectory()) {
            if (this.recursive) {
              fsu.rmdir_rf(filepath);
            } else {
              fs.rmDirSync(filepath);
            }
          } else {
            fs.unlinkSync(filepath);
          }
        } catch (_error) {
          err = _error;
          throw new Error(err);
        }
        return console.log(("" + 'Removed'.bold + " " + rpath).red);
      } else {
        return console.log(("" + 'Not found'.bold + " " + rpath).yellow);
      }
    };

    return Rm;

  })();

}).call(this);

/*
//@ sourceMappingURL=rm.map
*/
