// Generated by CoffeeScript 1.6.2
(function() {
  var Server, fork, path;

  path = require("path");

  fork = require("child_process").fork;

  module.exports = Server = (function() {
    Server.polvo = null;

    function Server(the, options) {
      this.the = the;
      this.polvo_path = path.join(this.the.root, 'node_modules', 'polvo', 'bin', 'polvo');
      fork(this.polvo_path, ['-ws'], {
        cwd: this.the.app_root
      });
    }

    return Server;

  })();

}).call(this);

/*
//@ sourceMappingURL=server.map
*/
